/**
 * AUTOGENERATED, DO NOT EDIT DIRECTLY!
 */

import * as remoteModel from '@quenk/jouvert/lib/app/remote/model';

/**
 * PostRemoteModel remote model (AUTOGENERATED).
 */
export class PostRemoteModel 
  extends 
  remoteModel.RemoteModel<Post> {

  static paths = {"search":"/r/posts/search","get":"/r/posts/{id}"}

  requests = new remoteModel.RequestFactory(PostRemoteModel.paths);


  create(id: Id,data: Comment) : Future<string> {
  

  }

}

