/**
 * AUTOGENERATED, DO NOT EDIT DIRECTLY!
 */

import * as remoteModel from '@quenk/jouvert/lib/app/remote/model';

/**
 * UserRemoteModel remote model (AUTOGENERATED).
 */
export class UserRemoteModel 
  extends 
  remoteModel.RemoteModel<User> {

  static paths = {"search":"invalid","get":"invalid"}

  paths = UserRemoteModel.paths;

}

