import * as _json from '@quenk/noni/lib/data/jsonx';




 
/**
 * SchemaNames type (AUTOGENERATED).
 */
export interface SchemaNames extends _json.Object {

  [key:string]: _json.Value

    'null'? : string

  }

