/**
 * AUTOGENERATED - DO NOT EDIT DIRECTLY!
 */
import * as mongodb from 'mongodb';
import * as BaseModel from '@quenk/dback-model-mongodb';


export {
  UserModel as ModelImpl,
  User as DataType
}

/**
 * UserModelModel for User (AUTOGENERATED).
 */
export class UserModel extends BaseModel<User> {

  constructor(
    public name: string,
    public database: mongodb.Db,
    public collection : mongodb.Collection) { super(database, collection); }

    id = 'username';

  static getInstance (db: mongodb.Db) : UserModel {

    return new UserModel('users', db, db.collection('users'));

  }

}

