#!/bin/bash
for schema in ./test/schema/*.json;
do
  ./node_modules/.bin/dagen --templates $(pwd)/data-validators \
  --template type.nunjucks \
  --plugin ./node_modules/@quenk/dagen-commons/lib/plugins/imports \
  --plugin ./node_modules/@quenk/dagen-commons/lib/plugins/validation \
  --namespace validators \
  "$schema" > test/data-validators/$(basename -s .json "$schema").ts && \
   \
  ./node_modules/.bin/dagen --templates $(pwd)/data-validators \
  --template test.nunjucks \
  --namespace validators \
  "$schema" > test/data-validators/$(basename -s .json "$schema")_test.ts
done

./node_modules/.bin/dagen --templates $(pwd)/data-validators \
--template index.nunjucks \
--namespace validators \
./test/schema/schemaNames.json > test/data-validators/index.ts
