
import { DateTime } from '../datetime';
import { Post } from '../data-types/post';
import * as _json from '@quenk/noni/lib/data/jsonx';
import * as _prec from '@quenk/preconditions';
import * as _numberPrec from '@quenk/preconditions/lib/number';
import * as _stringPrec from '@quenk/preconditions/lib/string';
import * as _recordPrec from '@quenk/preconditions/lib/record';
import * as _arrayPrec from '@quenk/preconditions/lib/array';

/**
 * @private Used during template generation.
 */
export type DataType = Post;

//@ts-ignore: 6133
const _boolean = _booleanPrec.toBoolean;

//@ts-ignore: 6133
const _number = _numberPrec.toNumber;

//@ts-ignore: 6133
const _string:_prec.Precondition<_json.Value, string> =
_prec.and(_stringPrec.isString, _stringPrec.trim);


/**
 * fieldValidators for Post (AUTOGENERATED).
 */ 
export const fieldValidators: _prec.Preconditions<_json.Value, _json.Value> = {
      'title' : _prec.and(_prec.notNull,           _string

),

      'tags' : _prec.and(_prec.notNull,     _prec.and(_arrayPrec.isArray, _arrayPrec.map(_prec.and(_prec.notNull,           _string

)))),

      'created_on' : _prec.and(_prec.notNull,           _prec.identity

),

      'created_by' : _prec.and(_prec.notNull,      _prec.and(_prec.notNull,           _number

))

};

/**
 * partialFieldValidators for Post (AUTOGENERATED).
 */ 
export const partialFieldValidators:_prec.Preconditions<_json.Value, _json.Value> = {
      'title' : _prec.and(_prec.notNull,           _string

),

      'tags' : _prec.and(_prec.notNull,     _prec.and(_arrayPrec.isArray, _arrayPrec.map(_prec.and(_prec.notNull,           _string

)))),

      'created_on' : _prec.and(_prec.notNull,           _prec.identity

),

      'created_by' : _prec.and(_prec.notNull,      _prec.and(_prec.notNull,           _number

))

};

/**
 * validate a value to determine if it satisfies the Post type
 * (AUTOGENERATED).
 */
export const validate: _prec.Precondition<_json.Value, Post> =
 _prec.and(
  _recordPrec.isRecord, 
  _recordPrec.restrict<_json.Value, _json.Value, Post>(fieldValidators)
 );

/**
 * validatePartial is like validate but only tests the keys that are encountered
 * (AUTOGENERATED).
 */
export const validatePartial: _prec.Precondition<_json.Value, Partial<Post>> =
 _prec.and(
  _recordPrec.isRecord, 
  _recordPrec.intersect<_json.Value, _json.Value, Post>(partialFieldValidators)
 );

