/**
 *AUTOGENERATED, DO NOT EDIT DIRECTLY. 
 */
import { Record } from '@quenk/noni/lib/data/record';

import _post from './post';
import _user from './user';

/**
 * Fields for mongodb projection.
 */
export interface Fields extends Record<number> {}

/**
 * fieldsAvailable from this module.
 */
export const fieldsAvailable: Record<Fields> = {


    'post': _post,

    'user': _user

}

