/**
 * AUTOGENERATED, DO NOT EDIT DIRECTLY!
 */

import * as http from '@quenk/jouvert/lib/app/model/http';

/**
 * PostHttpModel remote model (AUTOGENERATED).
 */
export class PostHttpModel 
  extends 
  http.HttpModel<Post> {

  static paths = {"search":"/r/posts/search","get":"/r/posts/{id}"}

  requests = new http.RequestFactory(PostHttpModel.paths);


  create(id: Id,data: Comment) : Future<string> {
  

  }

}

