/**
 * AUTOGENERATED, DO NOT EDIT DIRECTLY!
 */

import * as http from '@quenk/jouvert/lib/app/model/http';

/**
 * UserHttpModel remote model (AUTOGENERATED).
 */
export class UserHttpModel 
  extends 
  http.HttpModel<User> {

  static paths = {"search":"invalid","get":"invalid"}

  requests = new http.RequestFactory(UserHttpModel.paths);

}

