/**
 * AUTOGENERATED, DO NOT EDIT DIRECTLY!
 */

import * as http from '@quenk/jouvert/lib/app/model/http';
import * as json from '@quenk/noni/lib/data/jsonx';
import { Agent } from '@quenk/jhr/lib/agent';

/**
 * UserHttpModel remote model (AUTOGENERATED).
 */
export class UserHttpModel 
  extends 
  http.HttpModel<User> {

  static paths = {"search":"invalid","get":"invalid"}

  constructor(public agent: Agent<json.Object, json.Object>) {
    super(agent,  new http.RequestFactory(UserHttpModel.paths));
  }

}

