import * as _json from '@quenk/noni/lib/data/jsonx';




 
/**
 * Post type (AUTOGENERATED).
 *
 * This is a post type. 
 */
export interface Post extends _json.Object {

  [key:string]: _json.Value

    'id'? : number,

    'title'? : string,

    'body'? : string,

    'tags'? : string[],

    'group'? : {

  [key:string]: _json.Value

    'id'? : string,

    'name'? : string

  },

    'created_on'? : DateTime,

    'created_by'? : string|      number

  }


