import * as _json from '@quenk/noni/lib/data/jsonx';

/**
 * User type (AUTOGENERATED).
 */
export interface User extends _json.Object {

  [key:string]: _json.Value

    'id'? : number,

    'username'? : string,

    'email'? : string,

    'tags'? : string[],

    'last_login'? : string

  }


