import * as _json from '@quenk/noni/lib/data/jsonx';
/**
 * Post type (AUTOGENERATED).
 */
export interface Post extends _json.Object {
    [key: string]: _json.Value;
    'title'?: string;
    'body'?: string;
}
