/**
 *AUTOGENERATED, DO NOT EDIT DIRECTLY. 
 */
import { Record } from '@quenk/noni/lib/data/record';

import { FieldSet } from '@quenk/backend/lib/app/model';

import _post from './post';
import _schemanames from './schema-names';
import _user from './user';

/**
 * fieldsAvailable from this module.
 */
export const fieldsAvailable: Record<FieldSet> = {


    'post': _post,

    'schemanames': _schemanames,

    'user': _user

}

