/**
 * AUTOGENERATED - DO NOT EDIT DIRECTLY!
 */
 
import { unique } from '.';
import * as _json from '@quenk/noni/lib/data/jsonx';
import * as _prec from '@quenk/preconditions/lib/async';
import * as _recordPrec from '@quenk/preconditions/lib/async/record';
import * as _arrayPrec from '@quenk/preconditions/lib/async/array';

//@ts-ignore: 6133
const title = "Post";

//@ts-ignore: 6133
const _complete = _recordPrec.restrict;

//@ts-ignore: 6133
const _partial = _recordPrec.intersect;

/**
 * DataType checked.
 * 
 * Used by template generation.
 * @private 
 */
export type DataType = Post;

/**
 * fieldChecks for Post (AUTOGENERATED).
 */ 
export const fieldChecks: _prec.Preconditions<_json.Value, _json.Value> = {

    'title': _prec.every<_json.Value,_json.Value>(unique),

    'body': _prec.identity
};

/**
 * partialFieldChecks for Post (AUTOGENERATED).
 */ 
export const partialFieldChecks: _prec.Preconditions<_json.Value, _json.Value> = {

    'title': _prec.every<_json.Value,_json.Value>(unique),
    'body': _prec.identity};

/**
 * check a value to determine if it is a correct Post
 * (AUTOGENERATED).
 */
export const check: _prec.Precondition<_json.Value, Post> = 
    _prec.and<_json.Value, Post,Post>(
      _prec.async<_json.Value, Post>(validate),
       _recordPrec.restrict(fieldChecks));

/**
 * checkPartial is like check but only checks the fields encountered.
 * (AUTOGENERATED).
 */
 export const checkPartial: _prec.Precondition<_json.Value, Partial<Post>> = 
    _prec.and<_json.Value, Post,Post>(_prec.async<_json.Value,Post>(validatePartial), 
   _recordPrec.intersect(partialFieldChecks));  
